name: Pushwiki-CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: 0.0.0.${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        cache: yarn
    
    - run: yarn install

    - run: yarn build

    - name: Upload Full
      uses: actions/upload-artifact@v2
      with:
        name: pushwiki-full
        path: dist/

    - run: yarn build-slim

    - name: Upload Slim
      uses: actions/upload-artifact@v2
      with:
        name: pushwiki-slim
        path: dist/